steps:
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'docker/laravel/Dockerfile',
      '-t', 'gcr.io/${PROJECT_ID}/${_SERVICE}',
      '.'
    ]

  - id: 'push'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/${_SERVICE}']

  - id: 'migrate'
    name: 'gcr.io/google-appengine/exec-wrapper'
    args: [
      '-i', 'gcr.io/${PROJECT_ID}/${_SERVICE}',
      '-s', '${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}',
      '-e', 'PROJECT_ID=${PROJECT_ID}',
      '-e', 'APP_ENV=${_APP_ENV}',
      '-e', 'APP_DEBUG=${_APP_DEBUG}',
      '-e', 'DB_CONNECTION={_DB_CONNECTION}',
      '-e', 'DB_DATABASE=${_DB_DATABASE}',
      '-e', 'DB_USERNAME=${_DB_USERNAME}',
      '-e', 'DB_PASSWORD=${_DB_PASSWORD}',
      '-e', 'DB_SOCKET=${_DB_SOCKET}',
      '--', 'php', 'artisan', 'migrate'
    ]

  - id: 'deploy'
    name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '${_SERVICE}',
      '--platform', 'managed',
      '--region', '${_REGION}',
      '--image', 'gcr.io/${PROJECT_ID}/${_SERVICE}'
    ]
