version: "3.7"

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./:/var/www
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www
      - /var/www/vendor
    depends_on:
      - mysql

  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql/
      - ./docker/mysql/config/:/etc/mysql/conf.d
    ports:
      - "${DB_PORT}:3306"
